In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Admission%20Chance.csv')

In [ ]:
df.head()

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No          400 non-null    int64
 1   GRE Score          400 non-null    int64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    int64
 4    SOP               400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.3 KB

In [ ]:
df.describe()

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,115.614301,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,100.750000,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,200.500000,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,300.250000,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,400.000000,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [ ]:
df.columns

Index(['Serial No', 'GRE Score', 'TOEFL Score', 'University Rating', ' SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [ ]:
x=df[['GRE Score', 'TOEFL Score', 'University Rating', ' SOP',
       'LOR ', 'CGPA', 'Research']]
y=df[ 'Chance of Admit ']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=2529)
x_train

     GRE Score  TOEFL Score  University Rating   SOP  LOR   CGPA  Research
399        333          117                  4   5.0   4.0  9.66         1
195        307          107                  2   3.0   3.5  8.52         1
143        340          120                  4   4.5   4.0  9.92         1
217        321          109                  4   4.0   4.0  9.13         1
341        326          110                  3   3.5   3.5  8.76         1
..         ...          ...                ...   ...   ...   ...       ...
72         321          111                  5   5.0   5.0  9.45         1
228        318          112                  3   4.0   3.5  8.67         0
316        298          101                  2   1.5   2.0  7.86         0
50         313           98                  3   2.5   4.5  8.30         1
352        303          100                  2   3.0   3.5  8.06         1

[300 rows x 7 columns]

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

np.float64(-1.250445038169678)

In [ ]:
model.coef_

array([ 0.00178135,  0.00333643,  0.00448022, -0.00363339,  0.01931061,
        0.11349064,  0.02362743])

In [ ]:
y_pred=model.predict(x_test)
print(y_pred)

[0.7144961  0.72433652 0.6947035  0.66754341 0.5757752  0.92796592
 0.93381448 0.72160505 0.81332853 0.62087096 0.59814287 0.80197525
 0.52391907 0.79348618 0.84159249 0.66462736 0.65019659 0.66683741
 0.75633359 0.85990266 0.6611304  0.85530211 0.84773724 0.95084909
 0.68516577 0.65985861 0.65294588 0.57244986 0.56194295 0.57917889
 0.54339923 0.7596432  0.69747716 0.76966885 0.64849173 0.51748964
 0.4383084  0.84664962 0.90649863 0.8083248  0.71996237 0.72891493
 0.68158382 0.88586839 0.77418496 0.785911   0.95311821 0.88750419
 0.59732541 0.50982369 0.60049462 0.63438365 0.82802576 0.4489817
 0.71562113 0.77172062 0.69139158 0.6458718  0.85512273 0.65600333
 0.65360937 0.90885429 0.6353095  0.69091154 0.72239001 0.69413725
 0.59206369 0.93462023 0.59265576 0.91516448 0.59220822 0.93402829
 0.59535163 0.71363485 0.54648628 0.84450107 0.60806186 0.72368756
 0.68118959 0.81708514 0.7036384  0.88518239 0.67104593 0.53396146
 0.77947466 0.6577246  0.78501781 0.54737323 0.77588006 0.66836582
 0.69495794 0.69677332 0.92199533 0.70833475 0.62516322 0.61885063
 0.73937601 0.6724398  0.76000197 0.6220936 ]

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error

In [ ]:
mean_absolute_percentage_error(y_test,y_pred) #answer will be 8.23%

0.08239957446730994